### ISSUE TITLE
This repo should be a fork

### ISSUE THREAD

**Issue by warpech** [handsoncode-apps/SimplifiedOld#2]
This repository should be a GitHub Fork of https://github.com/starcountersamples/simplified

Otherwise it will be impossible to do a Pull Request.

**Comment by jakubklekota** [comment]
@warpech Now it's forked

**Comment by warpech** [comment]
Thanks! Closing

**Comment by warpech** [comment]
Can you enable the issue board at https://github.com/handsoncode-apps/Simplified ?

Then all the pending issues from https://github.com/handsoncode-apps/SimplifiedOld should be recreated there and this repo can be deleted.
